#cloud-config-mkdocs-system

groups:
  - ubuntu: [root,sys]
  - dpro42-group

users:
  - default
  - name: spiderman
    gecos: Peter Parker
    shell: /bin/bash
    primary_group: dpro42-group
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC8bJfR85v9E+M096iS8Tn5eqOD3BpjezKfbASwNA8Um azuread\aliaksandrrachok@EPGETBIW0398

runcmd:
  - touch /home/spiderman/hello.txt
  - echo "Hello! and welcome to this server! Destroy me when you are done!" >> /home/spiderman/hello.txt
  - sudo apt-get update
  - sudo apt install apache2 -q -y
  ## 4/1/2025: replaced pip install of mkdocs with apt-get install
  # old - sudo apt install python3-pip -y
  # old - sudo pip install mkdocs
  - sudo apt-get install mkdocs -q -y
  - sudo apt install awscli -q -y
  - sudo mkdir /home/spiderman/mkdocs
  - cd /home/spiderman/mkdocs
  - sudo mkdocs new mkdocs-project
  - cd mkdocs-project
  - sudo mkdocs build
  - sudo rm /var/www/html/index.html
  - sudo cp -R site/* /var/www/html
  - sudo mv /var/www/html/index.html /var/www/html/index1.html
  - sudo aws s3 cp s3://alexrachok-terraform-web-site-static-content/index.html /var/www/html/index.html
  - sudo systemctl restart apache2
  